#!/bin/sh

setxkbmap -device 18 -layout fr
sxhkd &
dunst &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

PRIMARY_MONITOR=`xrandr -q | grep " connected primary" | awk '{ print$1 }'`
PROFILE=mobile
if [[ "$PRIMARY_MONITOR" == "HDMI1" ]]; then
    PROFILE=docked
fi
HDMI_CONNECTED=`xrandr -q | grep "HDMI1 connected"`
if [[ "$PRIMARY_MONITOR" == "eDP1" && "$HDMI_CONNECTED" -ne "" ]]; then
    PROFILE=work
fi

AUTORANDR_CURRENT_PROFILE=$PROFILE ~/.config/autorandr/postswitch.d/bspwm
autorandr --change
~/.config/compton/launch.sh
~/.config/polybar/launch.sh
