#! /bin/sh

setxkbmap -option grp:alt_shift_toggle fr,us &
sxhkd &
~/.config/compton/launch.sh

autorandr --change
~/.config/autorandr/postswitch

bspc monitor -d code web office 4 5 6 7 8 discord slack

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill ~/Pictures/Wallpapers/leclerc.png

~/.config/polybar/launch.sh
